"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenFamily = void 0;
// Tipo/Familia de um token
var TokenFamily;
(function (TokenFamily) {
    TokenFamily[TokenFamily["TK_INT"] = 0] = "TK_INT";
    TokenFamily[TokenFamily["TK_FLOAT"] = 1] = "TK_FLOAT";
    TokenFamily[TokenFamily["TK_END"] = 2] = "TK_END";
    TokenFamily[TokenFamily["TK_CADEIA"] = 3] = "TK_CADEIA";
    TokenFamily[TokenFamily["TK_OR"] = 4] = "TK_OR";
    TokenFamily[TokenFamily["TK_AND"] = 5] = "TK_AND";
    TokenFamily[TokenFamily["TK_NOT"] = 6] = "TK_NOT";
    TokenFamily[TokenFamily["TK_DIV"] = 7] = "TK_DIV";
    TokenFamily[TokenFamily["TK_MULT"] = 8] = "TK_MULT";
    TokenFamily[TokenFamily["TK_MAIS"] = 9] = "TK_MAIS";
    TokenFamily[TokenFamily["TK_MENOS"] = 10] = "TK_MENOS";
    TokenFamily[TokenFamily["TK_DIF"] = 11] = "TK_DIF";
    TokenFamily[TokenFamily["TK_COMP"] = 12] = "TK_COMP";
    TokenFamily[TokenFamily["TK_ATRIB"] = 13] = "TK_ATRIB";
    TokenFamily[TokenFamily["TK_MENOR"] = 14] = "TK_MENOR";
    TokenFamily[TokenFamily["TK_MENOR_IGUAL"] = 15] = "TK_MENOR_IGUAL";
    TokenFamily[TokenFamily["TK_MAIOR"] = 16] = "TK_MAIOR";
    TokenFamily[TokenFamily["TK_MAIOR_IGUAL"] = 17] = "TK_MAIOR_IGUAL";
    TokenFamily[TokenFamily["TK_DATA"] = 18] = "TK_DATA";
    TokenFamily[TokenFamily["TK_RESERVADA"] = 19] = "TK_RESERVADA";
    TokenFamily[TokenFamily["TK_ID"] = 20] = "TK_ID";
    TokenFamily[TokenFamily["TK_ROTINA"] = 21] = "TK_ROTINA";
    TokenFamily[TokenFamily["TK_FIM_ROTINA"] = 22] = "TK_FIM_ROTINA";
    TokenFamily[TokenFamily["TK_SE"] = 23] = "TK_SE";
    TokenFamily[TokenFamily["TK_SENAO"] = 24] = "TK_SENAO";
    TokenFamily[TokenFamily["TK_IMPRIMA"] = 25] = "TK_IMPRIMA";
    TokenFamily[TokenFamily["TK_LEIA"] = 26] = "TK_LEIA";
    TokenFamily[TokenFamily["TK_PARA"] = 27] = "TK_PARA";
    TokenFamily[TokenFamily["TK_ENQUANTO"] = 28] = "TK_ENQUANTO";
    TokenFamily[TokenFamily["TK_DOIS_PONTOS"] = 29] = "TK_DOIS_PONTOS";
    TokenFamily[TokenFamily["TK_ABRE_PAR"] = 30] = "TK_ABRE_PAR";
    TokenFamily[TokenFamily["TK_FECHA_PAR"] = 31] = "TK_FECHA_PAR";
})(TokenFamily || (exports.TokenFamily = TokenFamily = {}));
